# Generated by Django 5.0.1 on 2024-01-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='edges',
            field=models.JSONField(default=dict),
        ),
    ]
