# Generated by Django 5.0.1 on 2024-01-15 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0002_alter_flow_edges'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
