# Generated by Django 5.0.1 on 2024-01-15 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0003_flow_created_at_flow_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
