# Generated by Django 5.0.1 on 2024-01-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0004_node_created_at_node_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flow',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='flow_id',
            new_name='flow',
        ),
    ]
