# Generated by Django 5.0.1 on 2024-01-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0005_rename_user_id_flow_user_rename_flow_id_node_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='x_pos',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='y_pos',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
