# Generated by Django 5.0.1 on 2024-02-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0006_node_x_pos_node_y_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
