# Generated by Django 5.0.1 on 2024-03-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0007_alter_node_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flow',
            old_name='edges',
            new_name='edges_map',
        ),
        migrations.AddField(
            model_name='flow',
            name='nodes_map',
            field=models.JSONField(default=dict),
        ),
    ]
