# Generated by Django 5.0.1 on 2024-03-01 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0009_alter_flow_edges_map_alter_flow_nodes_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='x_pos',
        ),
        migrations.RemoveField(
            model_name='node',
            name='y_pos',
        ),
    ]
