# Generated by Django 5.0.1 on 2024-03-13 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0010_remove_node_x_pos_remove_node_y_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareOptions',
            fields=[
                ('flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flows.flow')),
                ('view_url', models.URLField(blank=True, null=True)),
                ('comment_url', models.URLField(blank=True, null=True)),
                ('edit_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
