# Generated by Django 5.0.1 on 2024-03-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0012_rename_shareoptions_shareoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='edges_map',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='flow',
            name='nodes_map',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
