# Generated by Django 5.0.1 on 2024-03-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0013_alter_flow_edges_map_alter_flow_nodes_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareoption',
            name='access_pin',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
