# Generated by Django 5.0.1 on 2024-04-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0014_shareoption_access_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
