# Generated by Django 5.0.1 on 2024-04-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='product_description',
            field=models.CharField(max_length=500, null=True, verbose_name='Product description'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(verbose_name='Variant description'),
        ),
    ]
