# Generated by Django 5.0.1 on 2024-04-13 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscriptionplan_product_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.CharField(blank=True, max_length=30, verbose_name='Price'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['lemonsqueezy_id'], name='billing_sub_lemonsq_72018c_idx'),
        ),
    ]
