# Generated by Django 5.0.1 on 2024-04-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_subscription_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-lemonsqueezy_id']},
        ),
    ]
