# Generated by Django 5.0.1 on 2024-05-19 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flows', '0014_shareoption_access_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tags',
                'indexes': [models.Index(fields=['name'], name='tag_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlowTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flows.flow')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('tags', models.ManyToManyField(to='templating.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
