# Generated by Django 5.0.1 on 2024-04-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='Product id')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product name')),
                ('variant_id', models.IntegerField(unique=True, verbose_name='Variant id')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.CharField(max_length=30, verbose_name='Price')),
                ('is_usage_based', models.BooleanField(default=False, verbose_name='Is usage based')),
                ('interval', models.CharField(max_length=10, verbose_name='Interval')),
                ('interval_count', models.IntegerField(verbose_name='Interval count')),
                ('trial_interval', models.CharField(max_length=10, verbose_name='Trial interval')),
                ('trial_interval_count', models.IntegerField(verbose_name='Trial interval count')),
                ('sort', models.IntegerField(verbose_name='Sort')),
            ],
        ),
    ]
