# Generated by Django 5.0.1 on 2024-04-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='trial_interval',
            field=models.CharField(max_length=10, null=True, verbose_name='Trial interval'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='trial_interval_count',
            field=models.IntegerField(null=True, verbose_name='Trial interval count'),
        ),
    ]
