# Generated by Django 5.0.1 on 2024-04-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0002_alter_subscriptionplan_trial_interval_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['product_id']},
        ),
    ]
