# Generated by Django 5.0.1 on 2024-04-10 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0003_alter_subscriptionplan_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemonsqueezy_id', models.CharField(max_length=255, unique=True, verbose_name='Lemon Squeezy Id')),
                ('order_id', models.IntegerField(verbose_name='Order Id')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('status_formatted', models.CharField(max_length=100, verbose_name='Status Formatted')),
                ('renews_at', models.CharField(max_length=100, verbose_name='Renews At')),
                ('ends_at', models.CharField(max_length=100, verbose_name='Ends At')),
                ('trial_ends_at', models.CharField(max_length=100, verbose_name='Trial Ends At')),
                ('price', models.CharField(max_length=30, verbose_name='Price')),
                ('is_usage_based', models.BooleanField(default=False, verbose_name='Is usage based')),
                ('is_paused', models.BooleanField(default=False, verbose_name='Is paused')),
                ('subscription_item_id', models.BigIntegerField(null=True, verbose_name='Subscription Item Id')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription_plans.subscriptionplan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='subscriptio_user_id_835368_idx'), models.Index(fields=['plan'], name='subscriptio_plan_id_147174_idx')],
            },
        ),
    ]
